#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 002
# Task: Replace Mock JWT with Proper Cryptographic JWT Tokens

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task: JWT Authentication Security Fix"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK ENVIRONMENT
# ============================================

echo ""
echo "Checking environment..."

# Check if .env exists and has JWT_SECRET
if [ ! -f .env ]; then
    echo -e "${RED}Error: .env file not found${NC}"
    echo "Please create .env file from .env.example"
    exit 1
fi

if ! grep -q "JWT_SECRET" .env; then
    echo -e "${RED}Error: JWT_SECRET not found in .env${NC}"
    echo "Please add JWT_SECRET to your .env file"
    exit 1
fi

echo -e "${GREEN}Environment variables configured${NC}"

# Check if DATABASE_URL is set
if ! grep -q "DATABASE_URL" .env; then
    echo -e "${RED}Error: DATABASE_URL not found in .env${NC}"
    exit 1
fi

echo -e "${GREEN}Database configuration found${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
pnpm install

echo -e "${GREEN}Dependencies installed${NC}"

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."

# Start API server
echo "Starting API server..."
cd apps/api && pnpm dev &
API_PID=$!
cd ../..

wait_for_service 4000 "API Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  API:      http://localhost:4000"
echo "  Health:   http://localhost:4000/api/health"
echo "  GraphQL:  http://localhost:4000/graphql"
echo ""
echo "Security Info:"
echo "  Current:  Mock JWT tokens (Base64 only)"
echo "  Target:   Proper JWT with HS256 signature"
echo ""
echo "To stop services, press Ctrl+C"
echo ""

# Wait for user interrupt
trap "echo 'Stopping services...'; kill $API_PID 2>/dev/null; exit 0" INT TERM

wait
