/**
 * Component registry for Designsystemet components.
 * 
 * This registry provides metadata, usage guidelines, and examples for all
 * Designsystemet components available through @xala/ds.
 */

export interface ComponentInfo {
  /** Component identifier */
  id: string;
  /** Display name */
  name: string;
  /** Component category */
  category: 'feedback' | 'navigation' | 'input' | 'layout' | 'typography' | 'media' | 'utility' | 'composed' | 'block' | 'shell';
  /** Brief description */
  description: string;
  /** Import path from @xala/ds */
  importPath: string;
  /** Whether component supports the asChild pattern */
  supportsAsChild?: boolean;
  /** Accessibility features */
  a11yFeatures?: string[];
  /** Common use cases */
  useCases?: string[];
  /** Related components */
  related?: string[];
}

export const components: Record<string, ComponentInfo> = {
  // Feedback Components
  alert: {
    id: 'alert',
    name: 'Alert',
    category: 'feedback',
    description: 'Displays important messages with different severity levels (info, success, warning, error).',
    importPath: 'Alert',
    a11yFeatures: ['ARIA live regions', 'Role attribution', 'Keyboard accessible'],
    useCases: ['Form validation messages', 'System notifications', 'Status updates'],
    related: ['ErrorSummary'],
  },
  avatar: {
    id: 'avatar',
    name: 'Avatar',
    category: 'media',
    description: 'Displays user profile images or initials with customizable sizes.',
    importPath: 'Avatar',
    a11yFeatures: ['Alt text support', 'Semantic markup'],
    useCases: ['User profiles', 'Comments', 'Team member lists'],
  },
  badge: {
    id: 'badge',
    name: 'Badge',
    category: 'utility',
    description: 'Small status indicators for labeling and categorization.',
    importPath: 'Badge',
    a11yFeatures: ['Color contrast compliant', 'Screen reader friendly'],
    useCases: ['Status indicators', 'Tags', 'Notifications'],
  },
  chip: {
    id: 'chip',
    name: 'Chip',
    category: 'utility',
    description: 'Compact elements for filtering, selection, or input display.',
    importPath: 'Chip',
    supportsAsChild: true,
    a11yFeatures: ['Removable with keyboard', 'Focus management'],
    useCases: ['Filter pills', 'Selected items', 'Input tags'],
    related: ['Button'],
  },
  skeleton: {
    id: 'skeleton',
    name: 'Skeleton',
    category: 'utility',
    description: 'Loading placeholders that mimic the structure of content.',
    importPath: 'Skeleton',
    a11yFeatures: ['ARIA busy state', 'Screen reader announcements'],
    useCases: ['Content loading', 'Image placeholders', 'Form loading states'],
  },
  spinner: {
    id: 'spinner',
    name: 'Spinner',
    category: 'utility',
    description: 'Animated loading indicators for showing progress.',
    importPath: 'Spinner',
    a11yFeatures: ['ARIA live region', 'Descriptive text'],
    useCases: ['Button loading', 'Data fetching', 'Form submission'],
  },
  tooltip: {
    id: 'tooltip',
    name: 'Tooltip',
    category: 'utility',
    description: 'Contextual help text that appears on hover or focus.',
    importPath: 'Tooltip',
    a11yFeatures: ['Keyboard accessible', 'Delay timers', 'Focus trap'],
    useCases: ['Field descriptions', 'Icon explanations', 'Context help'],
  },

  // Navigation Components
  breadcrumbs: {
    id: 'breadcrumbs',
    name: 'Breadcrumbs',
    category: 'navigation',
    description: 'Hierarchical navigation trail showing the current page location.',
    importPath: 'Breadcrumbs',
    a11yFeatures: ['ARIA navigation landmarks', 'Keyboard navigation'],
    useCases: ['Site navigation', 'File system paths', 'Multi-step processes'],
  },
  link: {
    id: 'link',
    name: 'Link',
    category: 'navigation',
    description: 'Styled navigation links with consistent appearance.',
    importPath: 'Link',
    supportsAsChild: true,
    a11yFeatures: ['Focus visible', 'Screen reader announcements'],
    useCases: ['Internal navigation', 'External links', 'Action links'],
  },
  pagination: {
    id: 'pagination',
    name: 'Pagination',
    category: 'navigation',
    description: 'Navigation controls for paginated content.',
    importPath: 'Pagination',
    a11yFeatures: ['ARIA navigation labels', 'Page size announcements'],
    useCases: ['Data tables', 'Search results', 'Article listings'],
  },
  skipLink: {
    id: 'skipLink',
    name: 'SkipLink',
    category: 'navigation',
    description: 'Accessibility links for keyboard navigation to main content.',
    importPath: 'SkipLink',
    a11yFeatures: ['Skip to main content', 'Focus management'],
    useCases: ['Page accessibility', 'Keyboard navigation', 'Screen reader support'],
  },
  tabs: {
    id: 'tabs',
    name: 'Tabs',
    category: 'navigation',
    description: 'Tabbed interface for organizing content into sections.',
    importPath: 'Tabs',
    a11yFeatures: ['ARIA tab attributes', 'Keyboard navigation', 'Focus management'],
    useCases: ['Settings panels', 'Multi-page forms', 'Content organization'],
  },

  // Input Components
  button: {
    id: 'button',
    name: 'Button',
    category: 'input',
    description: 'Primary action element with multiple variants and sizes.',
    importPath: 'Button',
    supportsAsChild: true,
    a11yFeatures: ['Keyboard accessible', 'Focus visible', 'Disabled state'],
    useCases: ['Form submission', 'Dialog triggers', 'Navigation actions'],
    related: ['Link', 'Switch', 'ToggleGroup'],
  },
  checkbox: {
    id: 'checkbox',
    name: 'Checkbox',
    category: 'input',
    description: 'Binary selection input for multiple choices.',
    importPath: 'Checkbox',
    a11yFeatures: ['ARIA checked state', 'Keyboard navigation', 'Indeterminate state'],
    useCases: ['Multi-select options', 'Terms acceptance', 'Feature toggles'],
    related: ['Radio', 'Switch', 'Field'],
  },
  dropdown: {
    id: 'dropdown',
    name: 'Dropdown',
    category: 'input',
    description: 'Menu trigger with contextual actions or navigation.',
    importPath: 'Dropdown',
    a11yFeatures: ['ARIA menu attributes', 'Keyboard navigation', 'Focus trap'],
    useCases: ['Action menus', 'Navigation menus', 'Context menus'],
    related: ['Button', 'Select'],
  },
  errorSummary: {
    id: 'errorSummary',
    name: 'ErrorSummary',
    category: 'input',
    description: 'Collects and displays form validation errors.',
    importPath: 'ErrorSummary',
    a11yFeatures: ['Error links to fields', 'ARIA live regions', 'Focus management'],
    useCases: ['Form validation', 'Error reporting', 'Accessibility compliance'],
    related: ['Field', 'Alert'],
  },
  field: {
    id: 'field',
    name: 'Field',
    category: 'input',
    description: 'Form field wrapper with label, description, and error states.',
    importPath: 'Field',
    a11yFeatures: ['Label associations', 'Error descriptions', 'Required indicators'],
    useCases: ['Form layout', 'Input grouping', 'Validation states'],
    related: ['Input', 'Textarea', 'Select'],
  },
  fieldset: {
    id: 'fieldset',
    name: 'Fieldset',
    category: 'input',
    description: 'Groups related form fields with a common legend.',
    importPath: 'Fieldset',
    a11yFeatures: ['Field grouping', 'Legend associations'],
    useCases: ['Address forms', 'Payment details', 'Settings groups'],
    related: ['Field', 'Radio', 'Checkbox'],
  },
  input: {
    id: 'input',
    name: 'Input',
    category: 'input',
    description: 'Text input field with validation and formatting options.',
    importPath: 'Input',
    a11yFeatures: ['Input types', 'Validation attributes', 'Error states'],
    useCases: ['Text entry', 'Number input', 'Date/time input'],
    related: ['Field', 'Textfield', 'Textarea'],
  },
  radio: {
    id: 'radio',
    name: 'Radio',
    category: 'input',
    description: 'Single selection input from a group of options.',
    importPath: 'Radio',
    a11yFeatures: ['ARIA checked state', 'Group associations', 'Keyboard navigation'],
    useCases: ['Single choice options', 'Preference selection', 'Payment methods'],
    related: ['Checkbox', 'Switch', 'Fieldset'],
  },
  search: {
    id: 'search',
    name: 'Search',
    category: 'input',
    description: 'Search input with suggestions and autocomplete.',
    importPath: 'Search',
    a11yFeatures: ['ARIA autocomplete', 'Live regions', 'Keyboard navigation'],
    useCases: ['Site search', 'Data filtering', 'Autocomplete inputs'],
    related: ['Input', 'Suggestion'],
  },
  select: {
    id: 'select',
    name: 'Select',
    category: 'input',
    description: 'Dropdown selection from a list of options.',
    importPath: 'Select',
    a11yFeatures: ['ARIA attributes', 'Keyboard navigation', 'Multi-select support'],
    useCases: ['Option selection', 'Filter selection', 'Country picker'],
    related: ['Dropdown', 'Field'],
  },
  switch: {
    id: 'switch',
    name: 'Switch',
    category: 'input',
    description: 'Toggle switch for on/off binary states.',
    importPath: 'Switch',
    a11yFeatures: ['ARIA checked state', 'Keyboard toggle', 'State descriptions'],
    useCases: ['Feature toggles', 'Settings switches', 'Preferences'],
    related: ['Checkbox', 'Button', 'Field'],
  },
  textarea: {
    id: 'textarea',
    name: 'Textarea',
    category: 'input',
    description: 'Multi-line text input for longer content.',
    importPath: 'Textarea',
    a11yFeatures: ['Resize control', 'Character count', 'Validation'],
    useCases: ['Comments', 'Descriptions', 'Long text input'],
    related: ['Field', 'Input'],
  },
  textfield: {
    id: 'textfield',
    name: 'Textfield',
    category: 'input',
    description: 'Enhanced text input with icon and button support.',
    importPath: 'Textfield',
    a11yFeatures: ['Icon descriptions', 'Clear button', 'Input groups'],
    useCases: ['Search fields', 'Input with actions', 'Formatted inputs'],
    related: ['Input', 'Field', 'Search'],
  },
  toggleGroup: {
    id: 'toggleGroup',
    name: 'ToggleGroup',
    category: 'input',
    description: 'Group of toggle buttons for single or multiple selection.',
    importPath: 'ToggleGroup',
    a11yFeatures: ['ARIA pressed state', 'Group navigation', 'Multi-select mode'],
    useCases: ['Tool selection', 'View options', 'Format choices'],
    related: ['Button', 'Radio', 'Checkbox'],
  },

  // Layout Components
  card: {
    id: 'card',
    name: 'Card',
    category: 'layout',
    description: 'Container component for grouping related content.',
    importPath: 'Card',
    a11yFeatures: ['Semantic sections', 'Heading levels'],
    useCases: ['Content grouping', 'Dashboard widgets', 'Product cards'],
  },
  details: {
    id: 'details',
    name: 'Details',
    category: 'layout',
    description: 'Expandable/collapsible content section.',
    importPath: 'Details',
    a11yFeatures: ['ARIA expanded state', 'Keyboard toggle', 'Focus management'],
    useCases: ['FAQ sections', 'Advanced options', 'Content accordions'],
  },
  divider: {
    id: 'divider',
    name: 'Divider',
    category: 'layout',
    description: 'Visual separator for content sections.',
    importPath: 'Divider',
    a11yFeatures: ['Semantic separation', 'Color contrast'],
    useCases: ['Content sections', 'List separation', 'Visual breaks'],
  },
  list: {
    id: 'list',
    name: 'List',
    category: 'layout',
    description: 'Styled list components for consistent presentation.',
    importPath: 'List',
    a11yFeatures: ['List semantics', 'Nested lists', 'Keyboard navigation'],
    useCases: ['Data lists', 'Navigation lists', 'Content lists'],
  },
  table: {
    id: 'table',
    name: 'Table',
    category: 'layout',
    description: 'Data table with sorting, filtering, and pagination support.',
    importPath: 'Table',
    a11yFeatures: ['Table headers', 'Sort indicators', 'Row navigation'],
    useCases: ['Data grids', 'Reports', 'Comparison tables'],
  },

  // Typography Components
  tag: {
    id: 'tag',
    name: 'Tag',
    category: 'typography',
    description: 'Text styling component for emphasis and categorization.',
    importPath: 'Tag',
    a11yFeatures: ['Semantic markup', 'Color contrast'],
    useCases: ['Labels', 'Status text', 'Category indicators'],
  },

  // Other Components
  dialog: {
    id: 'dialog',
    name: 'Dialog',
    category: 'utility',
    description: 'Modal dialog for focused interactions and confirmations.',
    importPath: 'Dialog',
    a11yFeatures: ['Focus trap', 'ARIA attributes', 'Escape key', 'Backdrop click'],
    useCases: ['Confirmations', 'Form dialogs', 'Alert dialogs'],
  },
  popover: {
    id: 'popover',
    name: 'Popover',
    category: 'utility',
    description: 'Overlay container for contextual content and actions.',
    importPath: 'Popover',
    a11yFeatures: ['Focus management', 'Dismissal methods', 'Positioning'],
    useCases: ['Context menus', 'Tooltips with actions', 'Form helpers'],
    related: ['Tooltip', 'Dropdown'],
  },
  suggestion: {
    id: 'suggestion',
    name: 'Suggestion',
    category: 'utility',
    description: 'Autocomplete suggestion list for search and input fields.',
    importPath: 'Suggestion',
    a11yFeatures: ['ARIA attributes', 'Keyboard selection', 'Virtual scrolling'],
    useCases: ['Search autocomplete', 'Tag suggestions', 'Address autocomplete'],
    related: ['Search', 'Input', 'Select'],
  },

  // Composed Components
  contentLayout: {
    id: 'contentLayout',
    name: 'ContentLayout',
    category: 'composed',
    description: 'High-level layout component for page content with container, grid support, and header offset options.',
    importPath: 'ContentLayout',
    a11yFeatures: ['Container name for CSS queries', 'Semantic main landmark'],
    useCases: ['Page layouts', 'Dashboard grids', 'Content areas with fixed headers'],
    related: ['Container', 'Grid', 'ContentSection'],
  },
  contentSection: {
    id: 'contentSection',
    name: 'ContentSection',
    category: 'composed',
    description: 'Section component for grouping related content with optional title, subtitle, and fieldset wrapper.',
    importPath: 'ContentSection',
    a11yFeatures: ['Semantic fieldset', 'Heading hierarchy', 'Proper spacing'],
    useCases: ['Form sections', 'Content grouping', 'Settings panels'],
    related: ['ContentLayout', 'Fieldset', 'Heading'],
  },
  pageHeader: {
    id: 'pageHeader',
    name: 'PageHeader',
    category: 'composed',
    description: 'Consistent header component for pages with title, subtitle, breadcrumb, and action buttons.',
    importPath: 'PageHeader',
    a11yFeatures: ['Semantic heading', 'Flexible layout', 'Design system tokens'],
    useCases: ['Page headers', 'Section headers', 'Dashboard titles'],
    related: ['Breadcrumb', 'Heading', 'Button'],
  },
  appHeader: {
    id: 'appHeader',
    name: 'AppHeader',
    category: 'composed',
    description: 'Main application header with logo, search, and actions. Single-row layout following DIGILIST patterns.',
    importPath: 'AppHeader',
    a11yFeatures: ['Skip to main content link', 'Semantic header', 'Keyboard navigation', 'Responsive mobile layout'],
    useCases: ['Application headers', 'Site navigation', 'Global search'],
    related: ['HeaderLogo', 'HeaderSearch', 'HeaderActions', 'Container'],
  },
  headerLogo: {
    id: 'headerLogo',
    name: 'HeaderLogo',
    category: 'composed',
    description: 'Logo component for headers with image, title, subtitle, and optional link.',
    importPath: 'HeaderLogo',
    a11yFeatures: ['Semantic link', 'Alt text for images', 'Responsive layout'],
    useCases: ['Application branding', 'Site logos', 'Header navigation'],
    related: ['AppHeader'],
  },
  headerSearch: {
    id: 'headerSearch',
    name: 'HeaderSearch',
    category: 'composed',
    description: 'Search component with dropdown results, keyboard navigation, and grouped results support.',
    importPath: 'HeaderSearch',
    a11yFeatures: ['ARIA combobox', 'Keyboard navigation (arrows, enter, escape)', 'Screen reader announcements', 'Focus management'],
    useCases: ['Global search', 'Command palette', 'Quick navigation'],
    related: ['AppHeader', 'SearchIcon'],
  },
  headerActions: {
    id: 'headerActions',
    name: 'HeaderActions',
    category: 'composed',
    description: 'Actions container for header with proper spacing using design system tokens.',
    importPath: 'HeaderActions',
    a11yFeatures: ['Flexbox layout', 'Design system spacing'],
    useCases: ['Header action groups', 'Toolbar buttons', 'Navigation actions'],
    related: ['AppHeader', 'HeaderIconButton', 'Button'],
  },
  headerIconButton: {
    id: 'headerIconButton',
    name: 'HeaderIconButton',
    category: 'composed',
    description: 'Icon button with badge support for notifications and counters.',
    importPath: 'HeaderIconButton',
    a11yFeatures: ['ARIA labels', 'Badge count announcement', 'Keyboard accessible', 'Focus visible'],
    useCases: ['Notification icons', 'Shopping cart', 'Message indicators'],
    related: ['HeaderActions', 'Badge'],
  },
  navigation: {
    id: 'navigation',
    name: 'Navigation',
    category: 'composed',
    description: 'Horizontal navigation container following Designsystemet patterns.',
    importPath: 'Navigation',
    a11yFeatures: ['Semantic nav element', 'Flexbox layout', 'Design system spacing'],
    useCases: ['Main navigation', 'Tab navigation', 'Menu bars'],
    related: ['NavigationLink'],
  },
  navigationLink: {
    id: 'navigationLink',
    name: 'NavigationLink',
    category: 'composed',
    description: 'Navigation link with active state styling.',
    importPath: 'NavigationLink',
    a11yFeatures: ['Semantic anchor', 'Active state indication', 'Focus visible'],
    useCases: ['Navigation items', 'Tab items', 'Menu links'],
    related: ['Navigation', 'Link'],
  },
  filterBar: {
    id: 'filterBar',
    name: 'FilterBar',
    category: 'composed',
    description: 'Horizontal filter bar with primary filter, secondary filters, results count, and view mode toggle.',
    importPath: 'FilterBar',
    a11yFeatures: ['Semantic labels', 'Keyboard accessible', 'Clear visual hierarchy'],
    useCases: ['Rental object filters', 'Search refinement', 'View mode switching'],
    related: ['Select', 'Button', 'Grid'],
  },
  drawer: {
    id: 'drawer',
    name: 'Drawer',
    category: 'composed',
    description: 'Sliding panel component that can open from left, right, top, or bottom with overlay and keyboard support.',
    importPath: 'Drawer',
    a11yFeatures: ['ARIA dialog', 'Focus trap', 'Keyboard navigation (Escape to close)', 'Focus restoration', 'Body scroll lock'],
    useCases: ['Filter panels', 'Shopping carts', 'Mobile menus', 'Settings panels'],
    related: ['DrawerSection', 'DrawerItem', 'DrawerEmptyState'],
  },

  // Block Components
  listingCard: {
    id: 'listingCard',
    name: 'ListingCard',
    category: 'block',
    description: 'A reusable card component for displaying rental objects (spaces, resources, vehicles, events) with images, ratings, pricing, facilities, and action buttons. NOTE: "ListingCard" is a legacy component name.',
    importPath: 'ListingCard',
    a11yFeatures: ['Semantic HTML', 'Keyboard navigation', 'Screen reader labels', 'Focus management'],
    useCases: ['Rental object grid views in search results', 'Venue/resource cards on dashboards', 'Bookable space displays', 'Event displays'],
    related: ['ListingGrid', 'ListingListItem', 'ListingTableView'],
  },
  listingGrid: {
    id: 'listingGrid',
    name: 'ListingGrid',
    category: 'block',
    description: 'Responsive grid layout for displaying rental object cards with strict 3/2/1 column responsive pattern. NOTE: "ListingGrid" is a legacy component name.',
    importPath: 'ListingGrid',
    a11yFeatures: ['Responsive layout', 'Grid semantics'],
    useCases: ['Search results display', 'Rental object category pages', 'Dashboard views', 'Browse pages'],
    related: ['ListingCard', 'ListingToolbar'],
  },
  bookingFormModal: {
    id: 'bookingFormModal',
    name: 'BookingFormModal',
    category: 'block',
    description: 'Modal dialog for collecting booking details with comprehensive form validation.',
    importPath: 'BookingFormModal',
    a11yFeatures: ['Dialog focus trap', 'Form validation', 'Error messages', 'ARIA labels'],
    useCases: ['Booking confirmation flow', 'Time slot booking', 'Event registration', 'Resource reservation'],
    related: ['UnifiedBookingEngine', 'AvailabilityCalendar', 'BookingConfirmation'],
  },
  availabilityCalendar: {
    id: 'availabilityCalendar',
    name: 'AvailabilityCalendar',
    category: 'block',
    description: 'Weekly calendar grid with time slots for booking, supports selecting available slots and displays slot status.',
    importPath: 'AvailabilityCalendar',
    a11yFeatures: ['Keyboard navigation', 'Status labels', 'Focus management'],
    useCases: ['Time slot booking', 'Resource availability display', 'Meeting room booking', 'Appointment scheduling'],
    related: ['BookingFormModal', 'UnifiedBookingEngine'],
  },
  imageGallery: {
    id: 'imageGallery',
    name: 'ImageGallery',
    category: 'block',
    description: 'Hero image with vertical thumbnail sidebar for rental object detail pages.',
    importPath: 'ImageGallery',
    a11yFeatures: ['Alt text support', 'Keyboard navigation'],
    useCases: ['Rental object detail page hero', 'Product image galleries', 'Venue photo displays', 'Multi-image showcases'],
    related: ['ImageSlider', 'ListingDetailHeader'],
  },
  statCard: {
    id: 'statCard',
    name: 'StatCard',
    category: 'block',
    description: 'KPI/metric display card with value, trend indicator, and optional icon.',
    importPath: 'StatCard',
    a11yFeatures: ['Semantic markup', 'Clear value presentation'],
    useCases: ['Dashboard KPIs', 'Metric displays', 'Statistics overview', 'Performance indicators'],
    related: ['ActivityFeed', 'QuickActionCard'],
  },
  notificationBell: {
    id: 'notificationBell',
    name: 'NotificationBell',
    category: 'block',
    description: 'Notification icon with unread badge and dropdown.',
    importPath: 'NotificationBell',
    a11yFeatures: ['Badge count announcement', 'Dropdown navigation', 'Keyboard accessible'],
    useCases: ['Header notifications', 'Alert center', 'Message inbox'],
    related: ['NotificationCenter', 'NotificationItem'],
  },
  openingHoursCard: {
    id: 'openingHoursCard',
    name: 'OpeningHoursCard',
    category: 'block',
    description: 'Card displaying opening hours schedule.',
    importPath: 'OpeningHoursCard',
    a11yFeatures: ['Structured schedule data', 'Clear time display'],
    useCases: ['Venue opening hours', 'Availability schedule'],
    related: ['AvailabilityCalendar', 'ContactInfoCard'],
  },
  listingDetailHeader: {
    id: 'listingDetailHeader',
    name: 'ListingDetailHeader',
    category: 'block',
    description: 'Header section for rental object detail pages with title, location, and action buttons. NOTE: "ListingDetailHeader" is a legacy component name.',
    importPath: 'ListingDetailHeader',
    a11yFeatures: ['Semantic heading structure', 'Action button labels'],
    useCases: ['Rental object detail page headers', 'Venue page headers'],
    related: ['ImageGallery', 'KeyFactsRow'],
  },
  priceSummaryCard: {
    id: 'priceSummaryCard',
    name: 'PriceSummaryCard',
    category: 'block',
    description: 'Card displaying price breakdown with line items and total.',
    importPath: 'PriceSummaryCard',
    a11yFeatures: ['Clear price structure', 'Total emphasis'],
    useCases: ['Booking price summary', 'Cost breakdown', 'Invoice preview'],
    related: ['BookingFormModal', 'AdditionalServicesList'],
  },
  contactInfoCard: {
    id: 'contactInfoCard',
    name: 'ContactInfoCard',
    category: 'block',
    description: 'Card displaying contact information for rental objects.',
    importPath: 'ContactInfoCard',
    a11yFeatures: ['Link labels', 'Contact method semantics'],
    useCases: ['Rental object contact info', 'Venue contact details'],
    related: ['LocationCard', 'OpeningHoursCard'],
  },
  bookingSection: {
    id: 'bookingSection',
    name: 'BookingSection',
    category: 'block',
    description: 'Section wrapper for booking-related content on rental object detail pages.',
    importPath: 'BookingSection',
    a11yFeatures: ['Section semantics', 'Heading structure'],
    useCases: ['Rental object detail page booking area', 'Booking widget container'],
    related: ['UnifiedBookingEngine', 'AvailabilityCalendar'],
  },

  // Shell Components
  appShell: {
    id: 'appShell',
    name: 'AppShell',
    category: 'shell',
    description: 'Main application shell providing complete page layout with header, footer, and content areas. Flexbox-based layout with semantic HTML structure and responsive design.',
    importPath: 'AppShell',
    a11yFeatures: ['Semantic HTML5 landmarks (header, main, footer)', 'Flexible content area that grows to fill space', 'Design token-based colors for theme support', 'ForwardRef support for ref handling'],
    useCases: ['Application root layout', 'Full-page layouts with persistent header/footer', 'Admin dashboards', 'Public-facing web applications', 'Multi-page applications requiring consistent shell'],
    related: ['AppHeader', 'ContentLayout', 'ContentSection', 'Container'],
  },
};

export const componentCategories = {
  feedback: ['alert', 'skeleton', 'spinner'],
  navigation: ['breadcrumbs', 'link', 'pagination', 'skipLink', 'tabs'],
  input: [
    'button', 'checkbox', 'dropdown', 'errorSummary', 'field', 'fieldset',
    'input', 'radio', 'search', 'select', 'switch', 'textarea', 'textfield', 'toggleGroup'
  ],
  layout: ['card', 'details', 'divider', 'list', 'table'],
  typography: ['tag'],
  media: ['avatar'],
  utility: ['badge', 'chip', 'tooltip', 'dialog', 'popover', 'suggestion'],
  composed: [
    'contentLayout', 'contentSection', 'pageHeader', 'appHeader', 'headerLogo',
    'headerSearch', 'headerActions', 'headerIconButton', 'navigation', 'navigationLink',
    'filterBar', 'drawer'
  ],
  block: [
    'listingCard', 'listingGrid', 'bookingFormModal', 'availabilityCalendar',
    'imageGallery', 'statCard', 'notificationBell', 'openingHoursCard',
    'listingDetailHeader', 'priceSummaryCard', 'contactInfoCard', 'bookingSection'
  ],
  shell: ['appShell'],
} as const;

export type ComponentCategory = keyof typeof componentCategories;
export type ComponentId = keyof typeof components;
