import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Button, Fieldset, Select, Textfield, Heading, Alert } from '@xala/ds';
import { DesignsystemetProvider } from '@xala/ds';
import { DEFAULT_THEME, THEMES } from '@xala/ds-themes';
export function App() {
    const [theme, setTheme] = React.useState(DEFAULT_THEME);
    const [scheme, setScheme] = React.useState('auto');
    const [size, setSize] = React.useState('md');
    const themeOptions = Object.keys(THEMES);
    return (_jsx(DesignsystemetProvider, { theme: theme, colorScheme: scheme, size: size, children: _jsxs("div", { style: { padding: 24, maxWidth: 760, margin: '0 auto' }, children: [_jsx(Heading, { level: 1, children: "Xala + Designsystemet (Vite Monorepo)" }), _jsxs(Fieldset, { style: { marginBottom: 32 }, children: [_jsx(Heading, { level: 2, children: "Branding & display" }), _jsxs("div", { style: { display: 'grid', gap: 16 }, children: [_jsxs("div", { children: [_jsx("label", { htmlFor: "theme-select", children: "Theme" }), _jsx(Select, { id: "theme-select", value: theme, onChange: (e) => setTheme(e.target.value), children: themeOptions.map((id) => (_jsx("option", { value: id, children: id }, id))) })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "scheme-select", children: "Color scheme" }), _jsxs(Select, { id: "scheme-select", value: scheme, onChange: (e) => setScheme(e.target.value), children: [_jsx("option", { value: "auto", children: "auto" }), _jsx("option", { value: "light", children: "light" }), _jsx("option", { value: "dark", children: "dark" })] })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "size-select", children: "Size" }), _jsxs(Select, { id: "size-select", value: size, onChange: (e) => setSize(e.target.value), children: [_jsx("option", { value: "sm", children: "sm" }), _jsx("option", { value: "md", children: "md" }), _jsx("option", { value: "lg", children: "lg" })] })] }), _jsx(Textfield, { label: "Example field", placeholder: "Type something\u2026" }), _jsxs("div", { style: { display: 'flex', gap: 12, flexWrap: 'wrap' }, children: [_jsx(Button, { children: "Primary action" }), _jsx(Button, { variant: "secondary", children: "Secondary" }), _jsx(Button, { asChild: true, children: _jsx("a", { href: "https://designsystemet.no/no/", target: "_blank", rel: "noreferrer", children: "DS docs" }) })] })] })] }), _jsxs(Fieldset, { style: { marginBottom: 32 }, children: [_jsx(Heading, { level: 2, children: "Components" }), _jsx("div", { style: { display: 'grid', gap: 16 }, children: _jsx(Alert, { children: "This is an info alert showing the theme is working!" }) })] }), _jsx("p", { style: { marginTop: 24, opacity: 0.8 }, children: "Note: This repo uses Digdir Designsystemet themes. Theme switching is managed by the provider." })] }) }));
}
