#!/bin/bash

# Auto-Build Environment Setup - Rate Limiting Implementation
# Generated by Planner Agent
# Spec: 004-no-rate-limiting-on-authentication-endpoints

set -e

echo "========================================"
echo "Rate Limiting Implementation Setup"
echo "========================================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to wait for service
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -e "${YELLOW}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}✓ $name ready on port $port${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
cd apps/api
pnpm install
cd ../..
echo -e "${GREEN}✓ Dependencies installed${NC}"

# ============================================
# START API SERVICE
# ============================================

echo ""
echo "Starting API service..."

# Check if API is already running on port 4000
if lsof -Pi :4000 -sTCP:LISTEN -t >/dev/null 2>&1; then
    echo -e "${YELLOW}⚠ API already running on port 4000${NC}"
    echo -e "${YELLOW}  Stop existing process or skip this step${NC}"
else
    # Start API in background
    cd apps/api
    pnpm dev > /tmp/xaheen-api.log 2>&1 &
    API_PID=$!
    echo "API PID: $API_PID"
    cd ../..

    # Wait for API to be ready
    wait_for_service 4000 "API"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  API: http://localhost:4000"
echo ""
echo "Endpoints to Test:"
echo "  Health:  http://localhost:4000/health"
echo "  Auth:    http://localhost:4000/api/auth/login"
echo ""
echo "Next Steps:"
echo "  1. Implement rate limiting middleware"
echo "  2. Run security tests: cd apps/api && pnpm test:security"
echo "  3. Verify rate limits manually with curl"
echo ""
echo "To stop API:"
echo "  pkill -f 'tsx watch src/main.ts'"
echo ""
