/**
 * Economy Types
 * Types for invoice management, billing, and financial operations
 */

import type { TenantEntity, BaseQueryParams, ExportFormat } from './enums';

// =============================================================================
// Status Enums
// =============================================================================

export type InvoiceBasisStatus = 'draft' | 'approved' | 'invoiced' | 'cancelled';
export type SalesDocumentStatus = 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
export type CreditNoteStatus = 'draft' | 'approved' | 'processed' | 'cancelled';
export type VismaSyncStatus = 'not_synced' | 'pending' | 'synced' | 'failed';
export type InvoiceGenerationSource = 'manual' | 'booking' | 'batch';

// =============================================================================
// Line Item
// =============================================================================

export interface InvoiceLineItem {
  id: string;
  bookingId?: string;
  listingId?: string;
  listingName?: string;
  description: string;
  quantity: number;
  unitPrice: number;
  vatRate: number;
  vatAmount: number;
  amount: number;
  startTime?: string;
  endTime?: string;
}

// =============================================================================
// Invoice Basis (Fakturagrunnlag)
// =============================================================================

export interface InvoiceBasis extends TenantEntity {
  invoiceNumber?: string;
  bookingIds: string[];
  organizationId: string;
  organizationName?: string;
  lineItems: InvoiceLineItem[];
  subtotal: number;
  vatAmount: number;
  total: number;
  currency: string;
  status: InvoiceBasisStatus;
  notes?: string;
  generatedFrom: InvoiceGenerationSource;
  approvedAt?: string;
  approvedBy?: string;
}

export interface CreateInvoiceBasisDTO {
  bookingIds: string[];
  organizationId: string;
  lineItems: Omit<InvoiceLineItem, 'id'>[];
  notes?: string;
  generatedFrom?: InvoiceGenerationSource;
}

export interface UpdateInvoiceBasisDTO {
  lineItems?: Omit<InvoiceLineItem, 'id'>[];
  notes?: string;
}

export interface GenerateInvoicesFromBookingsDTO {
  startDate?: string;
  endDate?: string;
  organizationIds?: string[];
  listingIds?: string[];
  groupByOrganization?: boolean;
}

export interface GenerateInvoicesResponse {
  generated: number;
  invoiceBases: InvoiceBasis[];
}

// =============================================================================
// Sales Document (Salgsbilag)
// =============================================================================

export interface SalesDocument extends TenantEntity {
  invoiceNumber: string;
  invoiceBasisId?: string;
  organizationId: string;
  organizationName?: string;
  organizationAddress?: string;
  lineItems: InvoiceLineItem[];
  subtotal: number;
  vatAmount: number;
  total: number;
  currency: string;
  status: SalesDocumentStatus;
  invoiceDate: string;
  dueDate: string;
  paymentTerms: number;
  vismaInvoiceId?: string;
  vismaStatus?: VismaSyncStatus;
  lastSyncedAt?: string;
  syncError?: string;
  pdfUrl?: string;
  sentAt?: string;
  paidAt?: string;
  notes?: string;
}

export interface FinalizeInvoiceBasisDTO {
  invoiceBasisId: string;
  invoiceDate: string;
  paymentTerms: number;
  syncToVisma?: boolean;
}

export interface SendSalesDocumentDTO {
  salesDocumentId: string;
  email?: string;
  message?: string;
}

export interface MarkAsPaidDTO {
  salesDocumentId: string;
  paidAt?: string;
  paymentMethod?: string;
  transactionId?: string;
}

// =============================================================================
// Credit Note (Kreditnota)
// =============================================================================

export interface CreditNote extends TenantEntity {
  creditNoteNumber: string;
  originalInvoiceId: string;
  originalInvoiceNumber: string;
  organizationId: string;
  organizationName?: string;
  reason: string;
  lineItems: InvoiceLineItem[];
  subtotal: number;
  vatAmount: number;
  total: number;
  currency: string;
  status: CreditNoteStatus;
  creditDate: string;
  autoGenerated: boolean;
  bookingId?: string;
  approvedAt?: string;
  approvedBy?: string;
  processedAt?: string;
  pdfUrl?: string;
}

export interface CreateCreditNoteDTO {
  originalInvoiceId: string;
  reason: string;
  lineItems: Omit<InvoiceLineItem, 'id'>[];
  creditDate?: string;
  autoGenerated?: boolean;
  bookingId?: string;
}

// =============================================================================
// Visma Integration
// =============================================================================

export interface SyncToVismaDTO {
  salesDocumentIds: string[];
}

export interface SyncToVismaResponse {
  synced: string[];
  failed: Array<{
    id: string;
    error: string;
  }>;
}

export interface VismaStatusResponse {
  status: VismaSyncStatus;
  vismaInvoiceId?: string;
  lastSyncedAt?: string;
  syncError?: string;
}

// =============================================================================
// Query Params
// =============================================================================

export interface EconomyQueryParams extends BaseQueryParams {
  status?: string;
  organizationId?: string;
  startDate?: string;
  endDate?: string;
  vismaSyncStatus?: VismaSyncStatus;
  search?: string;
}

// =============================================================================
// Export
// =============================================================================

export interface EconomyExportParams {
  type: 'invoices' | 'credit-notes' | 'revenue' | 'vat-report';
  format: ExportFormat;
  startDate?: string;
  endDate?: string;
  organizationId?: string;
  status?: string[];
}

// =============================================================================
// Statistics & Summary
// =============================================================================

export interface EconomyStatistics {
  totalInvoices: number;
  totalRevenue: number;
  paidInvoices: number;
  unpaidInvoices: number;
  overdueInvoices: number;
  pendingCreditNotes: number;
  totalCreditNoteAmount: number;
  vismaSyncPending: number;
  averageInvoiceAmount: number;
  currency: string;
}
