#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 003: Add Security Headers

set -e

echo "========================================"
echo "Starting API Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check pnpm
if ! command -v pnpm &> /dev/null; then
    echo -e "${RED}Error: pnpm is not installed${NC}"
    echo "Install with: npm install -g pnpm@9.15.0"
    exit 1
fi
echo -e "${GREEN}✓ pnpm found${NC}"

# Check Node.js version
NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}Error: Node.js 20+ required (found: $(node -v))${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node -v)${NC}"

# Check DATABASE_URL environment variable
if [ -z "$DATABASE_URL" ]; then
    echo -e "${YELLOW}Warning: DATABASE_URL not set${NC}"
    echo "API may fail to start without database connection"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
pnpm install
echo -e "${GREEN}✓ Dependencies installed${NC}"

# ============================================
# START API SERVER
# ============================================

echo ""
echo "Starting API server..."
cd apps/api
pnpm dev &
API_PID=$!

# Wait for API to be ready
wait_for_service 4000 "API Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  API Server: http://localhost:4000"
echo ""
echo "Available endpoints:"
echo "  Health:   GET  http://localhost:4000/health"
echo "  GraphQL:  POST http://localhost:4000/graphql"
echo ""
echo "Run tests:"
echo "  Unit:     cd apps/api && pnpm test:unit"
echo "  Security: cd apps/api && pnpm test:security"
echo ""
echo "To test security headers manually:"
echo "  curl -sI http://localhost:4000/health"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Wait for user interrupt
wait $API_PID
