#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Task: Add horizontal scroll indicators for mobile filter tabs

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START MINSIDE APP
# ============================================

echo ""
echo "Starting Minside app..."
cd apps/minside && pnpm dev &
wait_for_service 5174 "Minside"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Minside:  http://localhost:5174"
echo ""
echo "Test URLs:"
echo "  Settings: http://localhost:5174/settings"
echo "  Bookings: http://localhost:5174/bookings"
echo ""
echo "To test mobile scroll indicators:"
echo "  1. Open browser dev tools (F12)"
echo "  2. Enable device toolbar (Ctrl+Shift+M)"
echo "  3. Select mobile device (iPhone SE, iPhone 12, etc.)"
echo "  4. Navigate to settings or bookings page"
echo "  5. Look for gradient indicators on scrollable areas"
echo ""
