#!/bin/bash
# =============================================================================
# Deployment Script for Xala Apps to Hostinger
# Usage: ./scripts/deploy.sh [web|backoffice|minside|all]
# =============================================================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Load configuration
if [ -f "$SCRIPT_DIR/deploy-config.sh" ]; then
    source "$SCRIPT_DIR/deploy-config.sh"
else
    echo -e "${RED}Error: deploy-config.sh not found!${NC}"
    echo "Please copy deploy-config.example.sh to deploy-config.sh and update values."
    exit 1
fi

# Function to print status
print_status() {
    echo -e "${BLUE}[DEPLOY]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# =============================================================================
# Safety Checks - Run before any deployment
# =============================================================================

# Check for duplicate Vite config files (prevents config conflicts)
check_duplicate_configs() {
    print_status "Checking for duplicate Vite configs..."
    
    for app in web backoffice minside; do
        local js_config="$PROJECT_ROOT/apps/$app/vite.config.js"
        local ts_config="$PROJECT_ROOT/apps/$app/vite.config.ts"
        
        if [ -f "$js_config" ] && [ -f "$ts_config" ]; then
            print_warning "Duplicate configs found in $app - removing stale .js file"
            rm "$js_config"
        fi
    done
    
    print_success "Config check passed"
}

# Ensure theme CSS files exist in public folders
ensure_theme_files() {
    print_status "Ensuring theme CSS files are in public folders..."
    
    local theme_src="$PROJECT_ROOT/packages/ds-themes"
    
    for app in web backoffice minside; do
        local theme_dir="$PROJECT_ROOT/apps/$app/public/themes"
        mkdir -p "$theme_dir"
        
        # Copy main theme
        if [ -f "$theme_src/generated/digilist.css" ]; then
            cp "$theme_src/generated/digilist.css" "$theme_dir/"
        else
            print_error "Missing: $theme_src/generated/digilist.css"
            exit 1
        fi
        
        # Copy extensions
        if [ -f "$theme_src/themes/digilist-extensions.css" ]; then
            cp "$theme_src/themes/digilist-extensions.css" "$theme_dir/"
        else
            print_warning "Missing: $theme_src/themes/digilist-extensions.css"
        fi
    done
    
    print_success "Theme files copied to all apps"
}

# Clear build caches to ensure fresh build
clear_caches() {
    print_status "Clearing build caches..."
    
    rm -rf "$PROJECT_ROOT/.turbo"
    rm -rf "$PROJECT_ROOT/node_modules/.cache"
    
    for app in web backoffice minside; do
        rm -rf "$PROJECT_ROOT/apps/$app/.turbo"
        rm -rf "$PROJECT_ROOT/apps/$app/node_modules/.vite"
        rm -rf "$PROJECT_ROOT/apps/$app/dist"
    done
    
    print_success "Caches cleared"
}

# Validate build output for circular dependency warnings
validate_build() {
    local app_name=$1
    local build_output=$2
    
    if echo "$build_output" | grep -qi "circular"; then
        print_error "Circular chunk dependency detected in $app_name!"
        print_error "Please check vite.config.ts manualChunks configuration."
        exit 1
    fi
}

# =============================================================================
# Build Functions
# =============================================================================

# Function to build an app
build_app() {
    local app_name=$1
    print_status "Building $app_name..."
    
    cd "$PROJECT_ROOT"
    
    # Create production env file
    create_prod_env "$app_name"
    
    # Build the app and capture output
    local build_output
    build_output=$(pnpm --filter "@xala/$app_name" build 2>&1)
    echo "$build_output"
    
    # Validate no circular dependencies
    validate_build "$app_name" "$build_output"
    
    print_success "$app_name built successfully!"
}

# Function to create production .env file
create_prod_env() {
    local app_name=$1
    local env_file="$PROJECT_ROOT/apps/$app_name/.env.production"
    
    print_status "Creating production environment for $app_name..."
    
    cat > "$env_file" << EOF
# Production Environment - Auto-generated by deploy.sh
VITE_API_URL=${VITE_API_URL}
VITE_WS_URL=${VITE_WS_URL}
VITE_TENANT_ID=${VITE_TENANT_ID}
EOF
    
    print_success "Created $env_file"
}

# Function to deploy an app
deploy_app() {
    local app_name=$1
    local dist_path=$2
    local remote_path=$3
    local subdomain=$4
    
    print_status "Deploying $app_name to $subdomain.$DOMAIN_BASE..."
    
    # Check if dist directory exists
    if [ ! -d "$PROJECT_ROOT/$dist_path" ]; then
        print_error "Build directory not found: $dist_path"
        print_warning "Run 'pnpm build' first or use deploy.sh which builds automatically."
        exit 1
    fi
    
    # Create remote directory if needed
    ssh -p "$HOSTINGER_PORT" "$HOSTINGER_USER@$HOSTINGER_HOST" \
        "mkdir -p $remote_path"
    
    # Sync files with rsync
    rsync -avz --delete \
        -e "ssh -p $HOSTINGER_PORT" \
        "$PROJECT_ROOT/$dist_path/" \
        "$HOSTINGER_USER@$HOSTINGER_HOST:$remote_path/"
    
    print_success "$app_name deployed to https://$subdomain.$DOMAIN_BASE"
}

# Function to deploy web app
deploy_web() {
    build_app "web"
    deploy_app "web" "$WEB_DIST" "$WEB_REMOTE_PATH" "$WEB_SUBDOMAIN"
}

# Function to deploy backoffice app
deploy_backoffice() {
    build_app "backoffice"
    deploy_app "backoffice" "$BACKOFFICE_DIST" "$BACKOFFICE_REMOTE_PATH" "$BACKOFFICE_SUBDOMAIN"
}

# Function to deploy minside app
deploy_minside() {
    build_app "minside"
    deploy_app "minside" "$MINSIDE_DIST" "$MINSIDE_REMOTE_PATH" "$MINSIDE_SUBDOMAIN"
}

# Function to show usage
show_usage() {
    echo "Usage: $0 [web|backoffice|minside|all]"
    echo ""
    echo "Commands:"
    echo "  web         Build and deploy web app"
    echo "  backoffice  Build and deploy backoffice app"
    echo "  minside     Build and deploy minside app"
    echo "  all         Build and deploy all apps"
    echo ""
    echo "Prerequisites:"
    echo "  1. Edit scripts/deploy-config.sh with your Hostinger details"
    echo "  2. Ensure SSH key is added to Hostinger server"
    echo "  3. Create A records for subdomains pointing to server IP"
}

# Main execution
main() {
    local target=${1:-""}
    
    if [ -z "$target" ]; then
        show_usage
        exit 1
    fi
    
    print_status "Starting deployment..."
    print_status "Target: $target"
    echo ""
    
    # Run safety checks BEFORE any build/deploy
    print_status "Running pre-flight checks..."
    check_duplicate_configs
    ensure_theme_files
    clear_caches
    echo ""
    
    case "$target" in
        web)
            deploy_web
            ;;
        backoffice)
            deploy_backoffice
            ;;
        minside)
            deploy_minside
            ;;
        all)
            deploy_web
            deploy_backoffice
            deploy_minside
            ;;
        *)
            print_error "Unknown target: $target"
            show_usage
            exit 1
            ;;
    esac
    
    echo ""
    print_success "Deployment complete!"
    echo ""
    echo "Next steps:"
    echo "  1. Verify sites are accessible:"
    echo "     - https://$WEB_SUBDOMAIN.$DOMAIN_BASE"
    echo "     - https://$BACKOFFICE_SUBDOMAIN.$DOMAIN_BASE"
    echo "     - https://$MINSIDE_SUBDOMAIN.$DOMAIN_BASE"
    echo ""
    echo "  2. If SSL not configured, run: ./scripts/setup-ssl.sh"
}

main "$@"
