#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 011
# Add Vite manual chunking strategy to backoffice app

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# VERIFY DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

if ! command -v pnpm &> /dev/null; then
    echo -e "${RED}pnpm not found. Please install pnpm first.${NC}"
    exit 1
fi

if ! command -v node &> /dev/null; then
    echo -e "${RED}node not found. Please install Node.js first.${NC}"
    exit 1
fi

echo -e "${GREEN}Dependencies OK${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
pnpm install

# ============================================
# START BACKOFFICE APP (DEV MODE)
# ============================================

echo ""
echo "Starting backoffice app..."
cd apps/backoffice && pnpm dev &
BACKOFFICE_PID=$!

wait_for_service 5175 "Backoffice"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backoffice: http://localhost:5175"
echo ""
echo "To stop services:"
echo "  kill $BACKOFFICE_PID"
echo ""
echo "Next steps:"
echo "  1. Modify apps/backoffice/vite.config.ts"
echo "  2. Add manual chunking configuration"
echo "  3. Test with: cd apps/backoffice && pnpm build"
echo "  4. Verify chunks in dist/assets/"
echo ""
